### ISSUE TITLE
Strymon submit hangs when job crashes

### ISSUE THREAD

**Issue by antiguru** [strymon-system/strymon-core#17]
A job that exists before properly initialized hangs the `strymon submit` command.

```
WARN:strymon_runtime::executor::executable: QueryId(0) E | error: Found argument '-w' which wasn't expected, or isn't valid in this context
WARN:strymon_runtime::executor::executable: QueryId(0) E | 
WARN:strymon_runtime::executor::executable: QueryId(0) E | USAGE:
WARN:strymon_runtime::executor::executable: QueryId(0) E |     timely_query_17673578641265549226 --batch <batch_size> --tick <tick_duration_millis>
WARN:strymon_runtime::executor::executable: QueryId(0) E | 
WARN:strymon_runtime::executor::executable: QueryId(0) E | For more information try --help
WARN:strymon_runtime::executor::executable: child exited with non-zero code: Some(1)
```

**Comment by gandro** [comment]
The reason why this happens is because a job is only considered "spawned" if the child process connects to the coordinator and announces itself. If this never happens, then the submission request is not cancelled until the user manually cancels it by killing `strymon submit`.

With the recent changes to how processes are managed in the executors, it is should now be possible to to detected a failed job process in the executor and report this to the coordinator. If the coordinator sees that the job is still in the `Spawning` state, it cancels the the request.

Additionally (but somewhat orthogonally), we should also implement timeouts for all RPC calls (with some exceptions like blocking topic lookups).
